### PR TITLE
IGNITE-13406 adding support for camel 3.x

### PR DESCRIPTION
**Pull request by scottmf**
This commit breaks compatibility with Camel 2.x

Closes https://issues.apache.org/jira/browse/IGNITE-13406

### CODE REVIEW

**Comment by samaitra** [comment]
Hi @scottmf Thank you for making the changes. I observed that the build for the PR failed (https://ci.ignite.apache.org/buildConfiguration/Tests_IgniteExtensions_Build/5587084?buildTab=log&focusLine=3&linesState=2010) due to missing dependencies in artifactory. 

I have made a separate PR for fix the dependencies error. 

https://github.com/apache/ignite-extensions/pull/22

**Comment by scottmf** [comment]
Thanks @samaitra I wasn't sure what was going on with that so I compiled the ignite 2.9.0-SNAPSHOT locally to get it all working.

**Review by samaitra — APPROVED** [review]
Changes looks good.

I will merge the PR after merging this PR #22

**Comment by samaitra** [comment]
@scottmf The build is green now

https://ci.ignite.apache.org/buildConfiguration/Tests_IgniteExtensions_Build/5589945

Thank you for your contribution.

**Pull request closed without merging**
